version: '1'
services: 

  docker:
   image: docker:latest
   volumes:
     - //var/run/docker.sock:/var/run/docker.sock
     - ./build.sh:/home/app/build.sh
     - ./docker-file.yaml:/home/compose/docker-file.yaml
   env_file:
     - ./build.env 
   command: sh -c
        "
          chmod +x /home/app/build.sh && 
         ./home/app/build.sh
        "
  
