version: '1'
services: 

  docker:
   image: docker:latest
   volumes:
     - //var/run/docker.sock:/var/run/docker.sock
     - ./build.sh:/home/app/build.sh
   env_file:
     - ./build.env 
   command: sh -c
        "
         apk add git &&
         git --version &&
         env && 
         cat /home/app/build.sh &&
         chmod +x /home/app/build.sh && 
         ./home/app/build.sh
        "
  
