version: '1'
services:

  web:
    image: student-enrollment-app-image:latest
    ports:  
      - 80:4200
    depends_on:
      - enrollment-api
    networks :
      - student-app-network

  enrollment-api:
      image: student-app-golang-image:latest
      ports:
        - 8080:8080
      networks: 
       - student-app-network
      environment:
       - DOMAIN=http://localhost:80
       - SOCKET_SERVER=http://socket-server:8082/update/status 
      depends_on:
        - stripe-cli

  stripehandler:
    image: stripe-handler:latest
    environment:
     - API_URL=http://enrollment-api
    depends_on:
      - socket-server
    networks:
      - student-app-network

  stripe-cli:
   image: stripe/stripe-cli
   container_name: stripe-cli
   environment:
    - STRIPE_API_KEY={stripe_api_key}
    - STRIPE_DEVICE_NAME=docker-1
   command: "listen --api-key STRIPE_API_KEY --device-name STRIPE_DEVICE_NAME --forward-to stripehandler:8081/webhooks"
   depends_on: 
      - stripehandler
   networks:
    - student-app-network 

  socket-server:
    image: socket-server:latest
    ports:
     - 8082:8082
    environment:
      - PORT=8082
      - ORIGIN=http://enrollment-api:8080
      - SOCKET_TIMEOUT=5000
      - SOCKET_CLIENT=http://localhost
    networks:
      - student-app-network


networks:
  student-app-network:
    driver: bridge
